---
title: "Instacart Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
install.packages("plotly")

library(plotly)
data("instacart")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
instacart %>%
  count(product_name, name = "n_orders") %>%
  top_n(10) %>%
  plot_ly(x = ~product_name, y = ~n_orders, color = ~product_name, type = "bar")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
instacart %>%
plot_ly(y = ~order_hour_of_day, color = ~department, type = "box",
          colors = "Set2")
```

### Chart C

```{r}
instacart %>%
  count(aisle, name = "n_orders_by_aisle") %>%
  arrange(desc(n_orders_by_aisle)) %>%
  top_n(30) %>%
plot_ly(
    x = ~aisle, y = ~n_orders_by_aisle, type = "scatter", mode = "markers", alpha = 0.5)
```

