---
title: "All Things Sarah"
output: 
  html_document:
  theme: journal
---

I'm a 25 year old student living in NYC.

I was born and raised in Arkansas- Go Razorbacks

<iframe src="https://giphy.com/embed/l1J9zzwIqWfBWJ9v2" width="480" height="244" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/secnetwork-college-football-sec-l1J9zzwIqWfBWJ9v2">via GIPHY</a></p>

I'm a big geek about the ocean, so I majored in marine biology at my undergraduate institution College of Charleston
<iframe src="https://giphy.com/embed/IW8v4AX8GgwM" width="480" height="270" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/ocean-IW8v4AX8GgwM">via GIPHY</a></p>

Scuba Diving is my absolute favorite activity, followed closely by traveling.

Sharks are my favorite animal, I advocate strongly for their conservation.

I'm infatuated with languages.
After college I moved to Thailand to teach Eglish for a year.
I loved it so much I moved to Spain to teach for another year.
My goal is to be trilingual by age 30 (don't ask about my progress..)

I love infectious diseases, as much as one could 'love' such a thing 

<iframe src="https://giphy.com/embed/xBIyz9QWatPdm" width="480" height="480" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/artists-on-tumblr-foxadhd-xBIyz9QWatPdm">via GIPHY</a></p>

After I complete this degree, I'm hoping to pursue work in the area of one health. I hope to get involved with infectious disease surveillance in wildlife, and seek opportunities to do lab work and field work abroad. 

Well there you have it that's the spark notes version of Sarah. Come back soon.

<iframe src="https://giphy.com/embed/Xj1GHC7mXPquY" width="480" height="231" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/parks-and-recreation-i-regret-nothing-ronswanson-Xj1GHC7mXPquY">via GIPHY</a></p>

