---
title: "Resume"
output: 
  html_document:
  theme: paper
---

**EDUCATION**

COLUMBIA UNIVERSITY                                                               _August 2018-Present_                                                              Master of Public Health in Epedimiology                                            Certificate in Toxicology

COLLEGE OF CHARLESTON                                                           _August 2012-May 2016_
Bachelor of Science in Marine Biology                                     Charleston, South Carolina
•	Cumulative GPA 3.5

SEMESTER AT SEA                                                                     _Spring 2015_
Study Abroad Program via University of Virginia                                  
Circumnavigated the globe on an academic voyage aboard the MV Explorer. Received a global comparative education while traveling to 12 countries throughout Southeast Asia, Africa, and Europe. 

BIMINI BIOLOGICAL FIELD STATION                                                     _Summer 2015_
Summer Research Experience                                                          Bimini, Bahamas
Shadowed and assisted marine biology research and data collection on sharks and rays at the Bimini lab.

BROADREACH                                                                          _Summer 2012_
Study Abroad Program                                                                Belize
Completed a marine biology course providing scuba certification and a specialized study focus on dolphin behavior and biology.

LAKESIDE HIGH SCHOOL                                                            _August 2008-May 2012_
Hot Springs, Arkansas
•	Cum Laude Honors Graduate                                                        
•	Student Council Vice President
•	Varsity Soccer & Volleyball


**WORK EXPERIENCE**

CULTURE AND LANGUAGE ASSISTANT			                                          _October 2017-June 2018_
CIEE Madrid, Spain
Full time work in a Spanish primary school to improve English language abilities in 4th, 5th and 6th grade. I collaborate with Spanish teachers to develop English in areas of language, natural science, social science, physical education, and art.

STEAD SCHOLARS							                                                      _June 2017-July 2017_
Arkansas Department of Health					 
Little Rock, Arkansas
Holistic introduction to public health and research collaboration with the Zoonotic Disease Division. Attended weekly grand rounds, epidemiology meetings, science advisory committees, and a graduate course at the UAMS College of Public Health. Produced and presented a project on mosquito abundance and composition.  

ENGLISH AS A SECOND LANGUAGE TEACHER                                            _October 2016-March 2017_
Anuban Samsen                                                                       Bangkok, Thailand
Taught advanced English curriculum to Thai students ages 6-12. Delivered creative and engaging lessons to develop skills in reading, writing, and speaking. Maintained classroom behavior and evaluated student progress throughout the course.    

INNKEEPER                                                                           _Summer 2016_
Lookout Point Lakeside Inn                                                        Hot Springs, Arkansas
Provided general management and upkeep of the bed and breakfast. Coordination of guest services included making reservations, answering phones, cooking, and cleaning, among other responsibilities. 

KAHUNA BAY MARINA							                                                       _Summer 2014_
Facilitated boat rentals and store purchases, as well as pumping oil and gas for customers. 

CAMP COUNSELOR                                                                        _Summer 2013_
Camp Winnamocka                                                                     Arkadelphia, Arkansas
Overnight adventure camp requiring 24-hour supervision and facilitation of outdoor activities for children ages 6-16.



